name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - master

env:
  RUN_REGION: us-central1
  RUN_IMAGE_TAG: gcr.io/${{ secrets.RUN_PROJECT_ID }}/${{ secrets.RUN_SERVICE_NAME }}:${{ github.sha }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT_ID }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |
        gcloud builds submit \
          --quiet \
          --tag $RUN_IMAGE_TAG

    # Deploy image to Cloud Run
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.RUN_SERVICE_NAME }} \
          --quiet \
          --region "$RUN_REGION" \
          --image "$RUN_IMAGE_TAG" \
          --platform "managed" \
          --allow-unauthenticated
